/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jp.visao;

import com.formdev.flatlaf.FlatDarkLaf;
//import java.io.BufferedInputStream;
import java.io.File;
import javafx.util.Duration;
//import java.io.FileInputStream;
import java.util.ArrayList;
//import javax.sound.sampled.AudioInputStream;
//import javax.sound.sampled.Clip;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
//import javazoom.jl.player.Player;
import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;

/**
 *
 * @author Woly
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    ArrayList<File> musicas = new ArrayList<File>();
    File musicaAtual = null;
    Media media = null;
    MediaPlayer player = null;
    //Player player;
    //Clip clip;
    //AudioInputStream ais;
    
    enum Estado {
        NAOABERTA, ABERTA
    };
    
    Estado estadoDaMusicaAtual = Estado.NAOABERTA;
    Duration duracao = null;
    
    public TelaPrincipal() {
        initComponents();
        adicionarTela(jInternalFrame1);
        jLabel2DPlayPause.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.setLocationRelativeTo(null);
    }
    
    public void adicionarTela(JInternalFrame tela){
        tela.setSize(jDesktopPane1.getPreferredSize());
        ((BasicInternalFrameUI)tela.getUI()).setNorthPane(null);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }
    
    public void abrirMusica(){
        media = new Media(musicaAtual.toURI().toString());
        
        duracao = media.getDuration();
        jSlider1.setMaximum((int) (duracao.toMillis()));
        jLabel2DDuracao.setText(minutos(duracao.toSeconds()));
        player = new MediaPlayer(media);
    }
    
    public String minutos(double tempoSegundos){
        
        int segundos = (int) (tempoSegundos);
        
        int minutos = segundos / 60;
        segundos = segundos % 60;
        
        String tempo = "";
        
        if(minutos > 9) tempo += minutos;
        else tempo += "0" + minutos;
        
        tempo += ":";
        
        if(segundos > 9) tempo += segundos;
        else tempo += "0" + segundos;
        
        return tempo;
    }
    
    public String extensao(File arquivo){
        String nomeDoArquivo = arquivo.getName();
        char letras[] = nomeDoArquivo.toCharArray();
        String extensao = "";
        
        for(int i = letras.length - 1; i >= 0 && letras[i] != '.'; i--){
            extensao += letras[i];
        }
        extensao = new StringBuilder(extensao).reverse().toString();
        return extensao;
    }
    
    public boolean eMusica(File arquivo){
        String extensoes[] = {
            "mp3", "wav", "flac"
        };
        
        String extensaoDoArquivo = extensao(arquivo);
        
        for(int i = 0; i < extensoes.length; i++){
            if(extensaoDoArquivo.equals(extensoes[i])){
                return true;
            }
        }
        
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2D1 = new com.jp.modelos.JLabel2D();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2D2 = new com.jp.modelos.JLabel2D();
        jLabel2DPlayPause = new com.jp.modelos.JLabel2D();
        jButton1 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel2DDuracao = new com.jp.modelos.JLabel2D();
        jLabel2DPosicao = new com.jp.modelos.JLabel2D();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(447, 273));
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(447, 273));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2D1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2D1.setText("Reprodutor");
        jLabel2D1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel2D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 450, -1));

        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 250, -1));

        jLabel2D2.setText("Músicas");
        jLabel2D2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel2D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel2DPlayPause.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2DPlayPause.setText("▶");
        jLabel2DPlayPause.setEnabled(false);
        jLabel2DPlayPause.setFont(new java.awt.Font("Yu Gothic UI", 0, 48)); // NOI18N
        jLabel2DPlayPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2DPlayPauseMouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jLabel2DPlayPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 80, 60));

        jButton1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton1.setText("🔍");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 40, 40));

        jSlider1.setMaximum(0);
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSlider1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider1MouseReleased(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 320, -1));

        jLabel2DDuracao.setText("00:00");
        jLabel2DDuracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel2DDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 40, -1));

        jLabel2DPosicao.setText("00:00");
        jLabel2DPosicao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel2DPosicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 40, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(60, 63, 65));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(447, 273));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ExploradorDeArquivos eda = new ExploradorDeArquivos();
        eda.setFileSelectionMode(ExploradorDeArquivos.DIRECTORIES_ONLY);
        eda.abrir(this);
        File diretorio = eda.getSelectedFile();
        if(diretorio != null && diretorio.isDirectory()){
            File arquivos[] = diretorio.listFiles();
            
            for(int i = 0; i < arquivos.length; i++){
                if(eMusica(arquivos[i])){
                    musicas.add(arquivos[i]);
                }
            }
            
            String musicasDaPasta[] = new String[musicas.size()];
            if(musicasDaPasta.length > 0){
                for(int i = 0; i < musicasDaPasta.length; i++){
                    File musica = musicas.get(i);
                    musicasDaPasta[i] = musica.getName().replace("." + extensao(musica), "");
                }

                jComboBox1.setModel(new DefaultComboBoxModel<>(musicasDaPasta));
                jComboBox1.setEnabled(true);
                jLabel2DPlayPause.setEnabled(true);
                musicaAtual = musicas.get(0);
                abrirMusica();
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2DPlayPauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2DPlayPauseMouseClicked
        // TODO add your handling code here:
        if(jLabel2DPlayPause.getText().equals("▶")){
            jLabel2DPlayPause.setText("II");
            if(estadoDaMusicaAtual == Estado.NAOABERTA){
                try {
                    player.play();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            

//            new Thread(){
//
//                public void run(){
//                    try {
//                        
//                    } catch (Exception e) {
//                        e.printStackTrace();
//                    }
//                }
//            }.run();
        }else{
            jLabel2DPlayPause.setText("▶");
            try{
                player.pause();
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jLabel2DPlayPauseMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(musicaAtual != musicas.get(jComboBox1.getSelectedIndex())){
            jLabel2DPlayPause.setText("▶");
            musicaAtual = musicas.get(jComboBox1.getSelectedIndex());
            abrirMusica();
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
        // TODO add your handling code here:
        int posicao = jSlider1.getValue();
        duracao = new Duration((double) (posicao));
        player.seek(duracao);
    }//GEN-LAST:event_jSlider1MouseReleased

    private void jSlider1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private com.jp.modelos.JLabel2D jLabel2D1;
    private com.jp.modelos.JLabel2D jLabel2D2;
    private com.jp.modelos.JLabel2D jLabel2DDuracao;
    private com.jp.modelos.JLabel2D jLabel2DPlayPause;
    private com.jp.modelos.JLabel2D jLabel2DPosicao;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
